# -*- coding: utf-8 -*-
"""ds_project5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16SYorkEYU34fFBWJhawf3Tzark1YItcq
"""

import kagglehub

path = kagglehub.dataset_download(
    "olistbr/brazilian-ecommerce"
)

print("Dataset Path:")
print(path)

import pandas as pd

orders_path = "orders.csv"

customers_path = "/kaggle/input/brazilian-ecommerce/olist_customers_dataset.csv"

order_items_path = "/kaggle/input/brazilian-ecommerce/olist_order_items_dataset.csv"

products_path = "/kaggle/input/brazilian-ecommerce/olist_products_dataset.csv"

orders_df = pd.read_csv(orders_path)

customers_df = pd.read_csv(customers_path)

order_items_df = pd.read_csv(order_items_path)

products_df = pd.read_csv(products_path)

print("===================================")
print("DATASETS LOADED SUCCESSFULLY")
print("===================================")

print("\nOrders Shape:", orders_df.shape)
print("Customers Shape:", customers_df.shape)
print("Order Items Shape:", order_items_df.shape)
print("Products Shape:", products_df.shape)

master_df = pd.merge(
    orders_df,
    customers_df,
    on='customer_id',
    how='inner'
)

master_df = pd.merge(
    master_df,
    order_items_df,
    on='order_id',
    how='inner'
)

master_df = pd.merge(
    master_df,
    products_df,
    on='product_id',
    how='left'
)

print("\nMASTER DATAFRAME CREATED")


print(master_df.head())

master_df['total_price'] = (
    master_df['price']
    +
    master_df['freight_value']
)

customer_revenue = (
    master_df
    .groupby('customer_unique_id')['total_price']
    .sum()
    .reset_index()
    .sort_values(
        by='total_price',
        ascending=False
    )
)


print("\nTOTAL REVENUE PER CUSTOMER")


print(customer_revenue.head(10))

customer_order_count = (
    master_df
    .groupby('customer_unique_id')['order_id']
    .nunique()
    .reset_index()
)

customer_order_count.columns = [
    'customer_unique_id',
    'total_orders'
]

single_order_customers = (
    customer_order_count[
        customer_order_count['total_orders'] == 1
    ]
)


print("\nCUSTOMERS WHO NEVER PLACED SECOND ORDER")


print(single_order_customers.head())

print("\nTotal Customers With One Order:")
print(len(single_order_customers))

master_df['order_purchase_timestamp'] = pd.to_datetime(
    master_df['order_purchase_timestamp']
)

master_df['order_year'] = (
    master_df['order_purchase_timestamp']
    .dt.year
)

master_df['order_month'] = (
    master_df['order_purchase_timestamp']
    .dt.month
)

print("\nYEAR AND MONTH EXTRACTION")


print(
    master_df[
        [
            'order_purchase_timestamp',
            'order_year',
            'order_month'
        ]
    ].head()
)

monthly_sales = (
    master_df
    .groupby(
        [
            'order_year',
            'order_month'
        ]
    )['total_price']
    .sum()
    .reset_index()
)

pivot_sales = pd.pivot_table(
    monthly_sales,
    values='total_price',
    index='order_year',
    columns='order_month',
    aggfunc='sum'
)

print("\nPIVOT TABLE")


print(pivot_sales)

melted_sales = pd.melt(
    pivot_sales.reset_index(),
    id_vars='order_year',
    var_name='Month',
    value_name='Sales'
)


print("\nMELTED DATAFRAME")


print(melted_sales.head(15))