# -*- coding: utf-8 -*-
"""DS_Project1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qd4JmGrh6t3jY0ypp4NUCMgGB82BtJb6
"""

#Student Grade Analyzer
import numpy as np
student_scores=np.random.randint(0, 100, size=50)
print(student_scores)
print(np.mean(student_scores))
print(np.median(student_scores))

print("\nHighest Score:")
print(np.max(student_scores))

print("\nLowest Score:")
print(np.min(student_scores))

print("\nNormalization:")
print((student_scores - np.min(student_scores)) / (np.max(student_scores) - np.min(student_scores)))

fail = student_scores[student_scores < 40]
print("\nFailed Students Scores:")
print(fail)

distinction = student_scores[student_scores > 85]
print("\nPassed Students Scores:")
print(distinction)

print("\nReshaped")
reshaped=student_scores.reshape(5,10)
print(reshaped)

print("\nAverage")
print(np.mean(reshaped,axis=1))