# -*- coding: utf-8 -*-
"""ds_project4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-mnRpQrJZLTogIYk_wUKf0ZNMRWIErZ0
"""

import pandas as pd
df=pd.read_csv("Sample - Superstore.csv",encoding='latin1')
print(df)

sales_profit = df.groupby(['Region', 'Category'])[['Sales', 'Profit']].sum()
print("\nTotal Sales and Profit by Region and Category:\n")
print(sales_profit)


top_subcategories = (
    df.groupby(['Region', 'Sub-Category'])['Sales']
    .sum()
    .reset_index()
)

top3 = top_subcategories.groupby('Region').apply(
    lambda x: x.nlargest(3, 'Sales')
)

print("\nTop 3 Performing Sub-Categories in Each Region:\n")
print(top3)




df['Profit Margin %'] = (df['Profit'] / df['Sales']) * 100

print("\nDataset with Profit Margin % column:\n")
print(df[['Sales', 'Profit', 'Profit Margin %']].head())




pivot_table = pd.pivot_table(
    df,
    values='Sales',
    index='Region',
    columns='Segment',
    aggfunc='mean'
)

print("\nAverage Sales by Region and Segment:\n")
print(pivot_table)



# Convert Order Date to datetime format
df['Order Date'] = pd.to_datetime(df['Order Date'])

# Extract month and year
df['Month'] = df['Order Date'].dt.to_period('M')

# Total profit month-wise
monthly_profit = df.groupby('Month')['Profit'].sum()
negative_profit_months = monthly_profit[monthly_profit < 0]

print("\nMonths with Negative Total Profit:\n")
print(negative_profit_months)