# -*- coding: utf-8 -*-
"""ds_project2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JkDQmfCGELKNmmXOlYEFc0XqWqCHMNGk
"""

import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np

img= mpimg.imread("flower.jpg")
plt.imshow(img)
plt.show()

gray = np.mean(img, axis=2)
plt.imshow(gray, cmap="gray")
plt.show()

#increase brightness
bright=np.clip(img + 50, 0, 255)
plt.imshow(bright.astype(np.uint8))
plt.show()

#decrease brightness
dark = np.clip(img - 50, 0, 255)
plt.imshow(dark.astype(np.uint8))
plt.show()

#Flip horizontally
print("\nHorizontal flip")
horizontal_flip = np.fliplr(img)
print(horizontal_flip)

# Flip vertically
print("\nvertically flip")
vertical_flip = np.flipud(img)
print(vertical_flip)

# Crop image
print("\nCropped image")
crop = img[100:300, 100:300]
print(crop)

# Display all images side-by-side
fig, ax = plt.subplots(2, 4, figsize=(16, 8))
ax[0,0].imshow(img)
ax[0,0].set_title("Original")

ax[0,1].imshow(gray, cmap="gray")
ax[0,1].set_title("Grayscale")

ax[0,2].imshow(bright.astype(np.uint8))
ax[0,2].set_title("Bright")

ax[0,3].imshow(dark.astype(np.uint8))
ax[0,3].set_title("Dark")

ax[1,0].imshow(horizontal_flip)
ax[1,0].set_title("Horizontal Flip")

ax[1,1].imshow(vertical_flip)
ax[1,1].set_title("Vertical Flip")

ax[1,2].imshow(crop)
ax[1,2].set_title("Crop")

ax[1,3].axis("off")

plt.tight_layout()
plt.show()