# -*- coding: utf-8 -*-
"""ds_project3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YYJpYiYUqVIzQYefKJMy0qH07EiYRuJ7
"""

import pandas as pd
df=pd.read_csv("matches.csv")
# print(df)

matches_per_season = df['season'].value_counts().sort_index()
print("\nMatches Played Each Season:\n")
print(matches_per_season)

most_wins = df['winner'].value_counts()
print("\nTeam with Most Wins:\n")
print(most_wins.head(1))

venue_name = "Wankhede Stadium"
venue_matches = df[df['venue'] == venue_name]
print(f"\nMatches played at {venue_name}:\n")
print(venue_matches[['team1', 'team2', 'winner', 'date']])

top_players = df['player_of_match'].value_counts().head(5)
print("\nTop 5 Player of the Match Winners:\n")
print(top_players)

df_clean = df.dropna()
print("\nDataset shape after dropping null values:")
print(df_clean.shape)